BEGIN;

CREATE TABLE team_likes (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id INTEGER NOT NULL
        REFERENCES users (id) ON DELETE CASCADE DEFERRABLE,
    team_id INTEGER NOT NULL
        REFERENCES teams (id) ON DELETE CASCADE DEFERRABLE,
    created_at TIMESTAMP NOT NULL DEFAULT NOW(),
    UNIQUE (user_id, team_id)
);

CREATE INDEX idx_team_likes_team_id ON team_likes (team_id);

INSERT INTO migrations (filename, applied_at)
VALUES ('005_add_team_likes.sql', NOW());

COMMIT;
