BEGIN;

CREATE TABLE follows (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    follower_id INTEGER NOT NULL
        REFERENCES users (id) ON DELETE CASCADE DEFERRABLE,
    followed_id INTEGER NOT NULL
        REFERENCES users (id) ON DELETE CASCADE DEFERRABLE,
    created_at TIMESTAMP NOT NULL DEFAULT NOW(),
    UNIQUE (follower_id, followed_id),
    CHECK (follower_id <> followed_id)
);

CREATE INDEX idx_follows_followed_id ON follows (followed_id);

INSERT INTO migrations (filename, applied_at)
VALUES ('006_add_follows.sql', NOW());

COMMIT;
