-- docs/database/seed-demo.sql
--
-- Fixed, idempotent demo dataset for exercising the social features:
-- 12 trainers, 29 teams, follows, and likes.
--
-- Safe to re-run: it only ever touches rows in the '@demo.brymon.local' namespace
-- (deleting the demo users cascades to their teams, team_pokemon, likes,
-- and follows). It never touches real accounts.
--
-- Apply:  psql -d brymon_team_builder -f docs/database/seed-demo.sql
-- Remove: DELETE FROM users WHERE email LIKE '%@demo.brymon.local';
--
-- Every demo account signs in with password:  DemoPass123!

BEGIN;

-- 1. Clear any existing demo data.
DELETE FROM users WHERE email LIKE '%@demo.brymon.local';

-- 2. Trainers.
INSERT INTO users
    (username, email, password_hash, role, email_verified_at,
     display_name, bio, avatar_pokemon_id)
VALUES
    ('demo_ashketchum', 'demo_ashketchum@demo.brymon.local', '$2y$12$ZdmrClL/hHZHrsQQDCHn7.rGHhBee8w4UeLi1I/l/v5yQn4oOPgom', 'user', NOW(), 'Ash K.', 'Gotta build ''em all. Kanto will always be home.', 25),
    ('demo_cynthia', 'demo_cynthia@demo.brymon.local', '$2y$12$ZdmrClL/hHZHrsQQDCHn7.rGHhBee8w4UeLi1I/l/v5yQn4oOPgom', 'user', NOW(), 'Cynthia', 'Sinnoh Champion. Dragons, grace, and a little mystery.', 445),
    ('demo_leon', 'demo_leon@demo.brymon.local', '$2y$12$ZdmrClL/hHZHrsQQDCHn7.rGHhBee8w4UeLi1I/l/v5yQn4oOPgom', 'user', NOW(), 'Leon', 'Undefeated Champion. Have a champion time!', 6),
    ('demo_nessa', 'demo_nessa@demo.brymon.local', '$2y$12$ZdmrClL/hHZHrsQQDCHn7.rGHhBee8w4UeLi1I/l/v5yQn4oOPgom', 'user', NOW(), 'Nessa', 'Hulbury gym leader. The tide always turns my way.', 130),
    ('demo_raihan', 'demo_raihan@demo.brymon.local', '$2y$12$ZdmrClL/hHZHrsQQDCHn7.rGHhBee8w4UeLi1I/l/v5yQn4oOPgom', 'user', NOW(), 'Raihan', 'Sandstorm teams and sunglasses. Strike a pose.', 373),
    ('demo_marnie', 'demo_marnie@demo.brymon.local', '$2y$12$ZdmrClL/hHZHrsQQDCHn7.rGHhBee8w4UeLi1I/l/v5yQn4oOPgom', 'user', NOW(), 'Marnie', 'Spikemuth born. Dark-type, every single slot.', 861),
    ('demo_hilda', 'demo_hilda@demo.brymon.local', '$2y$12$ZdmrClL/hHZHrsQQDCHn7.rGHhBee8w4UeLi1I/l/v5yQn4oOPgom', 'user', NOW(), 'Hilda', 'Crossed Unova on foot. Contrary Serperior believer.', 497),
    ('demo_gloria', 'demo_gloria@demo.brymon.local', '$2y$12$ZdmrClL/hHZHrsQQDCHn7.rGHhBee8w4UeLi1I/l/v5yQn4oOPgom', 'user', NOW(), 'Gloria', 'Galar rookie with a very large Dynamax button.', 869),
    ('demo_serena', 'demo_serena@demo.brymon.local', '$2y$12$ZdmrClL/hHZHrsQQDCHn7.rGHhBee8w4UeLi1I/l/v5yQn4oOPgom', 'user', NOW(), 'Serena', 'Kalos performer. Fairy typing is a fashion statement.', 700),
    ('demo_brendan', 'demo_brendan@demo.brymon.local', '$2y$12$ZdmrClL/hHZHrsQQDCHn7.rGHhBee8w4UeLi1I/l/v5yQn4oOPgom', 'user', NOW(), 'Brendan', 'Hoenn native. When in doubt, set the sun.', 254),
    ('demo_wallace', 'demo_wallace@demo.brymon.local', '$2y$12$ZdmrClL/hHZHrsQQDCHn7.rGHhBee8w4UeLi1I/l/v5yQn4oOPgom', 'user', NOW(), 'Wallace', 'Water is art. Milotic is the masterpiece.', 350),
    ('demo_n', 'demo_n@demo.brymon.local', '$2y$12$ZdmrClL/hHZHrsQQDCHn7.rGHhBee8w4UeLi1I/l/v5yQn4oOPgom', 'user', NOW(), 'N', 'Truth, ideals, and long conversations with Pokemon.', 571);

-- 3. Teams. Every name is unique so the FK lookups below are unambiguous.
INSERT INTO teams (user_id, name, notes, is_public, created_at)
VALUES
    ((SELECT id FROM users WHERE username = 'demo_ashketchum'), 'Kanto Classics', 'The team that started everything.', TRUE, NOW() - INTERVAL '20 days'),
    ((SELECT id FROM users WHERE username = 'demo_ashketchum'), 'Alola Ohana', 'Island trials, island family.', TRUE, NOW() - INTERVAL '12 days'),
    ((SELECT id FROM users WHERE username = 'demo_ashketchum'), 'Rental Randoms', 'Draft night experiment. Not ready yet.', FALSE, NOW() - INTERVAL '5 days'),
    ((SELECT id FROM users WHERE username = 'demo_cynthia'), 'Sinnoh Championship Squad', 'My Elite Four answer. Balanced and relentless.', TRUE, NOW() - INTERVAL '25 days'),
    ((SELECT id FROM users WHERE username = 'demo_cynthia'), 'Distortion World Detour', 'Built after a very strange afternoon.', TRUE, NOW() - INTERVAL '8 days'),
    ((SELECT id FROM users WHERE username = 'demo_leon'), 'Charizard and Friends', 'You already know slot one.', TRUE, NOW() - INTERVAL '22 days'),
    ((SELECT id FROM users WHERE username = 'demo_leon'), 'Galar Gauntlet', 'Full Galar starters plus steel and poison walls.', TRUE, NOW() - INTERVAL '10 days'),
    ((SELECT id FROM users WHERE username = 'demo_leon'), 'Battle Tower Boss', 'Six pseudo-legends and a Charizard. No notes.', TRUE, NOW() - INTERVAL '3 days'),
    ((SELECT id FROM users WHERE username = 'demo_nessa'), 'Hulbury Tides', 'Home gym line-up. Rock the boat.', TRUE, NOW() - INTERVAL '18 days'),
    ((SELECT id FROM users WHERE username = 'demo_nessa'), 'Rain Dance Party', 'Swift Swim and Drizzle. Bring an umbrella.', TRUE, NOW() - INTERVAL '6 days'),
    ((SELECT id FROM users WHERE username = 'demo_raihan'), 'Sandstorm Selfie Squad', 'Sand Stream up, cameras out.', TRUE, NOW() - INTERVAL '15 days'),
    ((SELECT id FROM users WHERE username = 'demo_raihan'), 'Dragon Den', 'Every typing is a dragon if you believe.', TRUE, NOW() - INTERVAL '9 days'),
    ((SELECT id FROM users WHERE username = 'demo_raihan'), 'Hammerlocke Heavies', 'Trap defense draft. Still tuning EVs.', FALSE, NOW() - INTERVAL '2 days'),
    ((SELECT id FROM users WHERE username = 'demo_marnie'), 'Spikemuth Punk', 'No gates, no rules, all Dark.', TRUE, NOW() - INTERVAL '14 days'),
    ((SELECT id FROM users WHERE username = 'demo_marnie'), 'Dark Alley', 'Priority, pressure, and bad attitudes.', TRUE, NOW() - INTERVAL '7 days'),
    ((SELECT id FROM users WHERE username = 'demo_hilda'), 'Unova Originals', 'Full starter trio plus the BW MVPs.', TRUE, NOW() - INTERVAL '19 days'),
    ((SELECT id FROM users WHERE username = 'demo_hilda'), 'Contrary Leaf Storm', 'Grass spam. It is a lifestyle.', TRUE, NOW() - INTERVAL '5 days'),
    ((SELECT id FROM users WHERE username = 'demo_gloria'), 'Dynamax Dreams', 'Press the button. Ask questions later.', TRUE, NOW() - INTERVAL '13 days'),
    ((SELECT id FROM users WHERE username = 'demo_gloria'), 'Wild Area Wanderers', 'Whatever wandered out of the tall grass.', TRUE, NOW() - INTERVAL '4 days'),
    ((SELECT id FROM users WHERE username = 'demo_gloria'), 'Rookie Roster', 'First real attempt at a defensive core.', FALSE, NOW() - INTERVAL '1 days'),
    ((SELECT id FROM users WHERE username = 'demo_serena'), 'Kalos Couture', 'Fairy and Psychic, coordinated to match.', TRUE, NOW() - INTERVAL '17 days'),
    ((SELECT id FROM users WHERE username = 'demo_serena'), 'Fairy Tale', 'Every slot resists Dragon. On purpose.', TRUE, NOW() - INTERVAL '6 days'),
    ((SELECT id FROM users WHERE username = 'demo_brendan'), 'Hoenn Heat', 'Starters plus the Hoenn power picks.', TRUE, NOW() - INTERVAL '21 days'),
    ((SELECT id FROM users WHERE username = 'demo_brendan'), 'Drought Offense', 'Sun up, Chlorophyll sweepers online.', TRUE, NOW() - INTERVAL '8 days'),
    ((SELECT id FROM users WHERE username = 'demo_brendan'), 'Weather Wars', 'Testing every weather setter at once. Chaos.', FALSE, NOW() - INTERVAL '3 days'),
    ((SELECT id FROM users WHERE username = 'demo_wallace'), 'Sootopolis Elegance', 'Gym team. Poise under pressure.', TRUE, NOW() - INTERVAL '16 days'),
    ((SELECT id FROM users WHERE username = 'demo_wallace'), 'Water Ballet', 'Bulky Water spam with just enough offense.', TRUE, NOW() - INTERVAL '5 days'),
    ((SELECT id FROM users WHERE username = 'demo_n'), 'Liberation Team', 'Fast, fragile, and full of conviction.', TRUE, NOW() - INTERVAL '15 days'),
    ((SELECT id FROM users WHERE username = 'demo_n'), 'Friends Not Tools', 'A team that just likes being a team.', TRUE, NOW() - INTERVAL '6 days');

-- 4. Team members.
INSERT INTO team_pokemon (team_id, pokemon_api_id, slot_number, pokemon_name)
VALUES
    ((SELECT id FROM teams WHERE name = 'Kanto Classics'), 3, 1, 'venusaur'),
    ((SELECT id FROM teams WHERE name = 'Kanto Classics'), 6, 2, 'charizard'),
    ((SELECT id FROM teams WHERE name = 'Kanto Classics'), 9, 3, 'blastoise'),
    ((SELECT id FROM teams WHERE name = 'Kanto Classics'), 143, 4, 'snorlax'),
    ((SELECT id FROM teams WHERE name = 'Kanto Classics'), 131, 5, 'lapras'),
    ((SELECT id FROM teams WHERE name = 'Kanto Classics'), 25, 6, 'pikachu'),
    ((SELECT id FROM teams WHERE name = 'Alola Ohana'), 724, 1, 'decidueye'),
    ((SELECT id FROM teams WHERE name = 'Alola Ohana'), 727, 2, 'incineroar'),
    ((SELECT id FROM teams WHERE name = 'Alola Ohana'), 730, 3, 'primarina'),
    ((SELECT id FROM teams WHERE name = 'Alola Ohana'), 745, 4, 'lycanroc'),
    ((SELECT id FROM teams WHERE name = 'Alola Ohana'), 778, 5, 'mimikyu'),
    ((SELECT id FROM teams WHERE name = 'Alola Ohana'), 25, 6, 'pikachu'),
    ((SELECT id FROM teams WHERE name = 'Rental Randoms'), 149, 1, 'dragonite'),
    ((SELECT id FROM teams WHERE name = 'Rental Randoms'), 94, 2, 'gengar'),
    ((SELECT id FROM teams WHERE name = 'Rental Randoms'), 65, 3, 'alakazam'),
    ((SELECT id FROM teams WHERE name = 'Rental Randoms'), 68, 4, 'machamp'),
    ((SELECT id FROM teams WHERE name = 'Rental Randoms'), 76, 5, 'golem'),
    ((SELECT id FROM teams WHERE name = 'Rental Randoms'), 59, 6, 'arcanine'),
    ((SELECT id FROM teams WHERE name = 'Sinnoh Championship Squad'), 445, 1, 'garchomp'),
    ((SELECT id FROM teams WHERE name = 'Sinnoh Championship Squad'), 442, 2, 'spiritomb'),
    ((SELECT id FROM teams WHERE name = 'Sinnoh Championship Squad'), 407, 3, 'roserade'),
    ((SELECT id FROM teams WHERE name = 'Sinnoh Championship Squad'), 448, 4, 'lucario'),
    ((SELECT id FROM teams WHERE name = 'Sinnoh Championship Squad'), 350, 5, 'milotic'),
    ((SELECT id FROM teams WHERE name = 'Sinnoh Championship Squad'), 468, 6, 'togekiss'),
    ((SELECT id FROM teams WHERE name = 'Distortion World Detour'), 445, 1, 'garchomp'),
    ((SELECT id FROM teams WHERE name = 'Distortion World Detour'), 423, 2, 'gastrodon'),
    ((SELECT id FROM teams WHERE name = 'Distortion World Detour'), 448, 3, 'lucario'),
    ((SELECT id FROM teams WHERE name = 'Distortion World Detour'), 471, 4, 'glaceon'),
    ((SELECT id FROM teams WHERE name = 'Distortion World Detour'), 229, 5, 'houndoom'),
    ((SELECT id FROM teams WHERE name = 'Distortion World Detour'), 474, 6, 'porygon-z'),
    ((SELECT id FROM teams WHERE name = 'Charizard and Friends'), 6, 1, 'charizard'),
    ((SELECT id FROM teams WHERE name = 'Charizard and Friends'), 887, 2, 'dragapult'),
    ((SELECT id FROM teams WHERE name = 'Charizard and Friends'), 681, 3, 'aegislash'),
    ((SELECT id FROM teams WHERE name = 'Charizard and Friends'), 612, 4, 'haxorus'),
    ((SELECT id FROM teams WHERE name = 'Charizard and Friends'), 479, 5, 'rotom'),
    ((SELECT id FROM teams WHERE name = 'Charizard and Friends'), 464, 6, 'rhyperior'),
    ((SELECT id FROM teams WHERE name = 'Galar Gauntlet'), 6, 1, 'charizard'),
    ((SELECT id FROM teams WHERE name = 'Galar Gauntlet'), 818, 2, 'inteleon'),
    ((SELECT id FROM teams WHERE name = 'Galar Gauntlet'), 812, 3, 'rillaboom'),
    ((SELECT id FROM teams WHERE name = 'Galar Gauntlet'), 815, 4, 'cinderace'),
    ((SELECT id FROM teams WHERE name = 'Galar Gauntlet'), 823, 5, 'corviknight'),
    ((SELECT id FROM teams WHERE name = 'Galar Gauntlet'), 748, 6, 'toxapex'),
    ((SELECT id FROM teams WHERE name = 'Battle Tower Boss'), 6, 1, 'charizard'),
    ((SELECT id FROM teams WHERE name = 'Battle Tower Boss'), 130, 2, 'gyarados'),
    ((SELECT id FROM teams WHERE name = 'Battle Tower Boss'), 445, 3, 'garchomp'),
    ((SELECT id FROM teams WHERE name = 'Battle Tower Boss'), 248, 4, 'tyranitar'),
    ((SELECT id FROM teams WHERE name = 'Battle Tower Boss'), 376, 5, 'metagross'),
    ((SELECT id FROM teams WHERE name = 'Battle Tower Boss'), 468, 6, 'togekiss'),
    ((SELECT id FROM teams WHERE name = 'Hulbury Tides'), 834, 1, 'drednaw'),
    ((SELECT id FROM teams WHERE name = 'Hulbury Tides'), 847, 2, 'barraskewda'),
    ((SELECT id FROM teams WHERE name = 'Hulbury Tides'), 279, 3, 'pelipper'),
    ((SELECT id FROM teams WHERE name = 'Hulbury Tides'), 748, 4, 'toxapex'),
    ((SELECT id FROM teams WHERE name = 'Hulbury Tides'), 130, 5, 'gyarados'),
    ((SELECT id FROM teams WHERE name = 'Hulbury Tides'), 195, 6, 'quagsire'),
    ((SELECT id FROM teams WHERE name = 'Rain Dance Party'), 279, 1, 'pelipper'),
    ((SELECT id FROM teams WHERE name = 'Rain Dance Party'), 847, 2, 'barraskewda'),
    ((SELECT id FROM teams WHERE name = 'Rain Dance Party'), 537, 3, 'seismitoad'),
    ((SELECT id FROM teams WHERE name = 'Rain Dance Party'), 272, 4, 'ludicolo'),
    ((SELECT id FROM teams WHERE name = 'Rain Dance Party'), 230, 5, 'kingdra'),
    ((SELECT id FROM teams WHERE name = 'Rain Dance Party'), 260, 6, 'swampert'),
    ((SELECT id FROM teams WHERE name = 'Sandstorm Selfie Squad'), 884, 1, 'duraludon'),
    ((SELECT id FROM teams WHERE name = 'Sandstorm Selfie Squad'), 844, 2, 'sandaconda'),
    ((SELECT id FROM teams WHERE name = 'Sandstorm Selfie Squad'), 526, 3, 'gigalith'),
    ((SELECT id FROM teams WHERE name = 'Sandstorm Selfie Squad'), 330, 4, 'flygon'),
    ((SELECT id FROM teams WHERE name = 'Sandstorm Selfie Squad'), 248, 5, 'tyranitar'),
    ((SELECT id FROM teams WHERE name = 'Sandstorm Selfie Squad'), 530, 6, 'excadrill'),
    ((SELECT id FROM teams WHERE name = 'Dragon Den'), 884, 1, 'duraludon'),
    ((SELECT id FROM teams WHERE name = 'Dragon Den'), 706, 2, 'goodra'),
    ((SELECT id FROM teams WHERE name = 'Dragon Den'), 330, 3, 'flygon'),
    ((SELECT id FROM teams WHERE name = 'Dragon Den'), 776, 4, 'turtonator'),
    ((SELECT id FROM teams WHERE name = 'Dragon Den'), 887, 5, 'dragapult'),
    ((SELECT id FROM teams WHERE name = 'Dragon Den'), 612, 6, 'haxorus'),
    ((SELECT id FROM teams WHERE name = 'Hammerlocke Heavies'), 248, 1, 'tyranitar'),
    ((SELECT id FROM teams WHERE name = 'Hammerlocke Heavies'), 450, 2, 'hippowdon'),
    ((SELECT id FROM teams WHERE name = 'Hammerlocke Heavies'), 530, 3, 'excadrill'),
    ((SELECT id FROM teams WHERE name = 'Hammerlocke Heavies'), 306, 4, 'aggron'),
    ((SELECT id FROM teams WHERE name = 'Hammerlocke Heavies'), 445, 5, 'garchomp'),
    ((SELECT id FROM teams WHERE name = 'Hammerlocke Heavies'), 423, 6, 'gastrodon'),
    ((SELECT id FROM teams WHERE name = 'Spikemuth Punk'), 861, 1, 'grimmsnarl'),
    ((SELECT id FROM teams WHERE name = 'Spikemuth Punk'), 877, 2, 'morpeko'),
    ((SELECT id FROM teams WHERE name = 'Spikemuth Punk'), 560, 3, 'scrafty'),
    ((SELECT id FROM teams WHERE name = 'Spikemuth Punk'), 454, 4, 'toxicroak'),
    ((SELECT id FROM teams WHERE name = 'Spikemuth Punk'), 862, 5, 'obstagoon'),
    ((SELECT id FROM teams WHERE name = 'Spikemuth Punk'), 510, 6, 'liepard'),
    ((SELECT id FROM teams WHERE name = 'Dark Alley'), 861, 1, 'grimmsnarl'),
    ((SELECT id FROM teams WHERE name = 'Dark Alley'), 197, 2, 'umbreon'),
    ((SELECT id FROM teams WHERE name = 'Dark Alley'), 461, 3, 'weavile'),
    ((SELECT id FROM teams WHERE name = 'Dark Alley'), 635, 4, 'hydreigon'),
    ((SELECT id FROM teams WHERE name = 'Dark Alley'), 625, 5, 'bisharp'),
    ((SELECT id FROM teams WHERE name = 'Dark Alley'), 630, 6, 'mandibuzz'),
    ((SELECT id FROM teams WHERE name = 'Unova Originals'), 497, 1, 'serperior'),
    ((SELECT id FROM teams WHERE name = 'Unova Originals'), 500, 2, 'emboar'),
    ((SELECT id FROM teams WHERE name = 'Unova Originals'), 503, 3, 'samurott'),
    ((SELECT id FROM teams WHERE name = 'Unova Originals'), 571, 4, 'zoroark'),
    ((SELECT id FROM teams WHERE name = 'Unova Originals'), 553, 5, 'krookodile'),
    ((SELECT id FROM teams WHERE name = 'Unova Originals'), 609, 6, 'chandelure'),
    ((SELECT id FROM teams WHERE name = 'Contrary Leaf Storm'), 497, 1, 'serperior'),
    ((SELECT id FROM teams WHERE name = 'Contrary Leaf Storm'), 549, 2, 'lilligant'),
    ((SELECT id FROM teams WHERE name = 'Contrary Leaf Storm'), 547, 3, 'whimsicott'),
    ((SELECT id FROM teams WHERE name = 'Contrary Leaf Storm'), 407, 4, 'roserade'),
    ((SELECT id FROM teams WHERE name = 'Contrary Leaf Storm'), 470, 5, 'leafeon'),
    ((SELECT id FROM teams WHERE name = 'Contrary Leaf Storm'), 598, 6, 'ferrothorn'),
    ((SELECT id FROM teams WHERE name = 'Dynamax Dreams'), 815, 1, 'cinderace'),
    ((SELECT id FROM teams WHERE name = 'Dynamax Dreams'), 812, 2, 'rillaboom'),
    ((SELECT id FROM teams WHERE name = 'Dynamax Dreams'), 818, 3, 'inteleon'),
    ((SELECT id FROM teams WHERE name = 'Dynamax Dreams'), 823, 4, 'corviknight'),
    ((SELECT id FROM teams WHERE name = 'Dynamax Dreams'), 861, 5, 'grimmsnarl'),
    ((SELECT id FROM teams WHERE name = 'Dynamax Dreams'), 887, 6, 'dragapult'),
    ((SELECT id FROM teams WHERE name = 'Wild Area Wanderers'), 841, 1, 'flapple'),
    ((SELECT id FROM teams WHERE name = 'Wild Area Wanderers'), 865, 2, 'sirfetchd'),
    ((SELECT id FROM teams WHERE name = 'Wild Area Wanderers'), 839, 3, 'coalossal'),
    ((SELECT id FROM teams WHERE name = 'Wild Area Wanderers'), 875, 4, 'eiscue'),
    ((SELECT id FROM teams WHERE name = 'Wild Area Wanderers'), 870, 5, 'falinks'),
    ((SELECT id FROM teams WHERE name = 'Wild Area Wanderers'), 877, 6, 'morpeko'),
    ((SELECT id FROM teams WHERE name = 'Rookie Roster'), 815, 1, 'cinderace'),
    ((SELECT id FROM teams WHERE name = 'Rookie Roster'), 823, 2, 'corviknight'),
    ((SELECT id FROM teams WHERE name = 'Rookie Roster'), 834, 3, 'drednaw'),
    ((SELECT id FROM teams WHERE name = 'Rookie Roster'), 836, 4, 'boltund'),
    ((SELECT id FROM teams WHERE name = 'Rookie Roster'), 826, 5, 'orbeetle'),
    ((SELECT id FROM teams WHERE name = 'Rookie Roster'), 832, 6, 'dubwool'),
    ((SELECT id FROM teams WHERE name = 'Kalos Couture'), 700, 1, 'sylveon'),
    ((SELECT id FROM teams WHERE name = 'Kalos Couture'), 655, 2, 'delphox'),
    ((SELECT id FROM teams WHERE name = 'Kalos Couture'), 282, 3, 'gardevoir'),
    ((SELECT id FROM teams WHERE name = 'Kalos Couture'), 683, 4, 'aromatisse'),
    ((SELECT id FROM teams WHERE name = 'Kalos Couture'), 671, 5, 'florges'),
    ((SELECT id FROM teams WHERE name = 'Kalos Couture'), 122, 6, 'mr-mime'),
    ((SELECT id FROM teams WHERE name = 'Fairy Tale'), 700, 1, 'sylveon'),
    ((SELECT id FROM teams WHERE name = 'Fairy Tale'), 468, 2, 'togekiss'),
    ((SELECT id FROM teams WHERE name = 'Fairy Tale'), 730, 3, 'primarina'),
    ((SELECT id FROM teams WHERE name = 'Fairy Tale'), 778, 4, 'mimikyu'),
    ((SELECT id FROM teams WHERE name = 'Fairy Tale'), 861, 5, 'grimmsnarl'),
    ((SELECT id FROM teams WHERE name = 'Fairy Tale'), 858, 6, 'hatterene'),
    ((SELECT id FROM teams WHERE name = 'Hoenn Heat'), 254, 1, 'sceptile'),
    ((SELECT id FROM teams WHERE name = 'Hoenn Heat'), 257, 2, 'blaziken'),
    ((SELECT id FROM teams WHERE name = 'Hoenn Heat'), 260, 3, 'swampert'),
    ((SELECT id FROM teams WHERE name = 'Hoenn Heat'), 282, 4, 'gardevoir'),
    ((SELECT id FROM teams WHERE name = 'Hoenn Heat'), 306, 5, 'aggron'),
    ((SELECT id FROM teams WHERE name = 'Hoenn Heat'), 330, 6, 'flygon'),
    ((SELECT id FROM teams WHERE name = 'Drought Offense'), 324, 1, 'torkoal'),
    ((SELECT id FROM teams WHERE name = 'Drought Offense'), 3, 2, 'venusaur'),
    ((SELECT id FROM teams WHERE name = 'Drought Offense'), 6, 3, 'charizard'),
    ((SELECT id FROM teams WHERE name = 'Drought Offense'), 38, 4, 'ninetales'),
    ((SELECT id FROM teams WHERE name = 'Drought Offense'), 103, 5, 'exeggutor'),
    ((SELECT id FROM teams WHERE name = 'Drought Offense'), 485, 6, 'heatran'),
    ((SELECT id FROM teams WHERE name = 'Weather Wars'), 279, 1, 'pelipper'),
    ((SELECT id FROM teams WHERE name = 'Weather Wars'), 186, 2, 'politoed'),
    ((SELECT id FROM teams WHERE name = 'Weather Wars'), 248, 3, 'tyranitar'),
    ((SELECT id FROM teams WHERE name = 'Weather Wars'), 460, 4, 'abomasnow'),
    ((SELECT id FROM teams WHERE name = 'Weather Wars'), 324, 5, 'torkoal'),
    ((SELECT id FROM teams WHERE name = 'Weather Wars'), 38, 6, 'ninetales'),
    ((SELECT id FROM teams WHERE name = 'Sootopolis Elegance'), 350, 1, 'milotic'),
    ((SELECT id FROM teams WHERE name = 'Sootopolis Elegance'), 130, 2, 'gyarados'),
    ((SELECT id FROM teams WHERE name = 'Sootopolis Elegance'), 272, 3, 'ludicolo'),
    ((SELECT id FROM teams WHERE name = 'Sootopolis Elegance'), 340, 4, 'whiscash'),
    ((SELECT id FROM teams WHERE name = 'Sootopolis Elegance'), 73, 5, 'tentacruel'),
    ((SELECT id FROM teams WHERE name = 'Sootopolis Elegance'), 121, 6, 'starmie'),
    ((SELECT id FROM teams WHERE name = 'Water Ballet'), 350, 1, 'milotic'),
    ((SELECT id FROM teams WHERE name = 'Water Ballet'), 134, 2, 'vaporeon'),
    ((SELECT id FROM teams WHERE name = 'Water Ballet'), 131, 3, 'lapras'),
    ((SELECT id FROM teams WHERE name = 'Water Ballet'), 423, 4, 'gastrodon'),
    ((SELECT id FROM teams WHERE name = 'Water Ballet'), 748, 5, 'toxapex'),
    ((SELECT id FROM teams WHERE name = 'Water Ballet'), 479, 6, 'rotom-wash'),
    ((SELECT id FROM teams WHERE name = 'Liberation Team'), 571, 1, 'zoroark'),
    ((SELECT id FROM teams WHERE name = 'Liberation Team'), 523, 2, 'zebstrika'),
    ((SELECT id FROM teams WHERE name = 'Liberation Team'), 567, 3, 'archeops'),
    ((SELECT id FROM teams WHERE name = 'Liberation Team'), 565, 4, 'carracosta'),
    ((SELECT id FROM teams WHERE name = 'Liberation Team'), 555, 5, 'darmanitan'),
    ((SELECT id FROM teams WHERE name = 'Liberation Team'), 561, 6, 'sigilyph'),
    ((SELECT id FROM teams WHERE name = 'Friends Not Tools'), 571, 1, 'zoroark'),
    ((SELECT id FROM teams WHERE name = 'Friends Not Tools'), 579, 2, 'reuniclus'),
    ((SELECT id FROM teams WHERE name = 'Friends Not Tools'), 526, 3, 'gigalith'),
    ((SELECT id FROM teams WHERE name = 'Friends Not Tools'), 584, 4, 'vanilluxe'),
    ((SELECT id FROM teams WHERE name = 'Friends Not Tools'), 601, 5, 'klinklang'),
    ((SELECT id FROM teams WHERE name = 'Friends Not Tools'), 591, 6, 'amoonguss');

-- 5. Follows.
INSERT INTO follows (follower_id, followed_id, created_at)
VALUES
    ((SELECT id FROM users WHERE username = 'demo_ashketchum'),
     (SELECT id FROM users WHERE username = 'demo_cynthia'), NOW()),
    ((SELECT id FROM users WHERE username = 'demo_ashketchum'),
     (SELECT id FROM users WHERE username = 'demo_leon'), NOW()),
    ((SELECT id FROM users WHERE username = 'demo_ashketchum'),
     (SELECT id FROM users WHERE username = 'demo_brendan'), NOW()),
    ((SELECT id FROM users WHERE username = 'demo_cynthia'),
     (SELECT id FROM users WHERE username = 'demo_leon'), NOW()),
    ((SELECT id FROM users WHERE username = 'demo_cynthia'),
     (SELECT id FROM users WHERE username = 'demo_wallace'), NOW()),
    ((SELECT id FROM users WHERE username = 'demo_cynthia'),
     (SELECT id FROM users WHERE username = 'demo_n'), NOW()),
    ((SELECT id FROM users WHERE username = 'demo_leon'),
     (SELECT id FROM users WHERE username = 'demo_cynthia'), NOW()),
    ((SELECT id FROM users WHERE username = 'demo_leon'),
     (SELECT id FROM users WHERE username = 'demo_raihan'), NOW()),
    ((SELECT id FROM users WHERE username = 'demo_leon'),
     (SELECT id FROM users WHERE username = 'demo_nessa'), NOW()),
    ((SELECT id FROM users WHERE username = 'demo_nessa'),
     (SELECT id FROM users WHERE username = 'demo_leon'), NOW()),
    ((SELECT id FROM users WHERE username = 'demo_nessa'),
     (SELECT id FROM users WHERE username = 'demo_raihan'), NOW()),
    ((SELECT id FROM users WHERE username = 'demo_nessa'),
     (SELECT id FROM users WHERE username = 'demo_wallace'), NOW()),
    ((SELECT id FROM users WHERE username = 'demo_nessa'),
     (SELECT id FROM users WHERE username = 'demo_marnie'), NOW()),
    ((SELECT id FROM users WHERE username = 'demo_raihan'),
     (SELECT id FROM users WHERE username = 'demo_leon'), NOW()),
    ((SELECT id FROM users WHERE username = 'demo_raihan'),
     (SELECT id FROM users WHERE username = 'demo_cynthia'), NOW()),
    ((SELECT id FROM users WHERE username = 'demo_raihan'),
     (SELECT id FROM users WHERE username = 'demo_brendan'), NOW()),
    ((SELECT id FROM users WHERE username = 'demo_marnie'),
     (SELECT id FROM users WHERE username = 'demo_n'), NOW()),
    ((SELECT id FROM users WHERE username = 'demo_marnie'),
     (SELECT id FROM users WHERE username = 'demo_hilda'), NOW()),
    ((SELECT id FROM users WHERE username = 'demo_marnie'),
     (SELECT id FROM users WHERE username = 'demo_leon'), NOW()),
    ((SELECT id FROM users WHERE username = 'demo_hilda'),
     (SELECT id FROM users WHERE username = 'demo_n'), NOW()),
    ((SELECT id FROM users WHERE username = 'demo_hilda'),
     (SELECT id FROM users WHERE username = 'demo_cynthia'), NOW()),
    ((SELECT id FROM users WHERE username = 'demo_hilda'),
     (SELECT id FROM users WHERE username = 'demo_serena'), NOW()),
    ((SELECT id FROM users WHERE username = 'demo_gloria'),
     (SELECT id FROM users WHERE username = 'demo_leon'), NOW()),
    ((SELECT id FROM users WHERE username = 'demo_gloria'),
     (SELECT id FROM users WHERE username = 'demo_marnie'), NOW()),
    ((SELECT id FROM users WHERE username = 'demo_gloria'),
     (SELECT id FROM users WHERE username = 'demo_nessa'), NOW()),
    ((SELECT id FROM users WHERE username = 'demo_gloria'),
     (SELECT id FROM users WHERE username = 'demo_raihan'), NOW()),
    ((SELECT id FROM users WHERE username = 'demo_serena'),
     (SELECT id FROM users WHERE username = 'demo_cynthia'), NOW()),
    ((SELECT id FROM users WHERE username = 'demo_serena'),
     (SELECT id FROM users WHERE username = 'demo_wallace'), NOW()),
    ((SELECT id FROM users WHERE username = 'demo_serena'),
     (SELECT id FROM users WHERE username = 'demo_hilda'), NOW()),
    ((SELECT id FROM users WHERE username = 'demo_brendan'),
     (SELECT id FROM users WHERE username = 'demo_raihan'), NOW()),
    ((SELECT id FROM users WHERE username = 'demo_brendan'),
     (SELECT id FROM users WHERE username = 'demo_wallace'), NOW()),
    ((SELECT id FROM users WHERE username = 'demo_brendan'),
     (SELECT id FROM users WHERE username = 'demo_leon'), NOW()),
    ((SELECT id FROM users WHERE username = 'demo_wallace'),
     (SELECT id FROM users WHERE username = 'demo_cynthia'), NOW()),
    ((SELECT id FROM users WHERE username = 'demo_wallace'),
     (SELECT id FROM users WHERE username = 'demo_nessa'), NOW()),
    ((SELECT id FROM users WHERE username = 'demo_wallace'),
     (SELECT id FROM users WHERE username = 'demo_serena'), NOW()),
    ((SELECT id FROM users WHERE username = 'demo_n'),
     (SELECT id FROM users WHERE username = 'demo_hilda'), NOW()),
    ((SELECT id FROM users WHERE username = 'demo_n'),
     (SELECT id FROM users WHERE username = 'demo_marnie'), NOW()),
    ((SELECT id FROM users WHERE username = 'demo_n'),
     (SELECT id FROM users WHERE username = 'demo_cynthia'), NOW());

-- 6. Likes.
INSERT INTO team_likes (user_id, team_id, created_at)
VALUES
    ((SELECT id FROM users WHERE username = 'demo_ashketchum'),
     (SELECT id FROM teams WHERE name = 'Sinnoh Championship Squad'), NOW()),
    ((SELECT id FROM users WHERE username = 'demo_ashketchum'),
     (SELECT id FROM teams WHERE name = 'Charizard and Friends'), NOW()),
    ((SELECT id FROM users WHERE username = 'demo_ashketchum'),
     (SELECT id FROM teams WHERE name = 'Battle Tower Boss'), NOW()),
    ((SELECT id FROM users WHERE username = 'demo_ashketchum'),
     (SELECT id FROM teams WHERE name = 'Hoenn Heat'), NOW()),
    ((SELECT id FROM users WHERE username = 'demo_ashketchum'),
     (SELECT id FROM teams WHERE name = 'Unova Originals'), NOW()),
    ((SELECT id FROM users WHERE username = 'demo_cynthia'),
     (SELECT id FROM teams WHERE name = 'Charizard and Friends'), NOW()),
    ((SELECT id FROM users WHERE username = 'demo_cynthia'),
     (SELECT id FROM teams WHERE name = 'Battle Tower Boss'), NOW()),
    ((SELECT id FROM users WHERE username = 'demo_cynthia'),
     (SELECT id FROM teams WHERE name = 'Dragon Den'), NOW()),
    ((SELECT id FROM users WHERE username = 'demo_cynthia'),
     (SELECT id FROM teams WHERE name = 'Water Ballet'), NOW()),
    ((SELECT id FROM users WHERE username = 'demo_cynthia'),
     (SELECT id FROM teams WHERE name = 'Liberation Team'), NOW()),
    ((SELECT id FROM users WHERE username = 'demo_leon'),
     (SELECT id FROM teams WHERE name = 'Sinnoh Championship Squad'), NOW()),
    ((SELECT id FROM users WHERE username = 'demo_leon'),
     (SELECT id FROM teams WHERE name = 'Sandstorm Selfie Squad'), NOW()),
    ((SELECT id FROM users WHERE username = 'demo_leon'),
     (SELECT id FROM teams WHERE name = 'Dragon Den'), NOW()),
    ((SELECT id FROM users WHERE username = 'demo_leon'),
     (SELECT id FROM teams WHERE name = 'Unova Originals'), NOW()),
    ((SELECT id FROM users WHERE username = 'demo_leon'),
     (SELECT id FROM teams WHERE name = 'Hoenn Heat'), NOW()),
    ((SELECT id FROM users WHERE username = 'demo_leon'),
     (SELECT id FROM teams WHERE name = 'Kalos Couture'), NOW()),
    ((SELECT id FROM users WHERE username = 'demo_nessa'),
     (SELECT id FROM teams WHERE name = 'Charizard and Friends'), NOW()),
    ((SELECT id FROM users WHERE username = 'demo_nessa'),
     (SELECT id FROM teams WHERE name = 'Sandstorm Selfie Squad'), NOW()),
    ((SELECT id FROM users WHERE username = 'demo_nessa'),
     (SELECT id FROM teams WHERE name = 'Sootopolis Elegance'), NOW()),
    ((SELECT id FROM users WHERE username = 'demo_nessa'),
     (SELECT id FROM teams WHERE name = 'Water Ballet'), NOW()),
    ((SELECT id FROM users WHERE username = 'demo_nessa'),
     (SELECT id FROM teams WHERE name = 'Dark Alley'), NOW()),
    ((SELECT id FROM users WHERE username = 'demo_raihan'),
     (SELECT id FROM teams WHERE name = 'Charizard and Friends'), NOW()),
    ((SELECT id FROM users WHERE username = 'demo_raihan'),
     (SELECT id FROM teams WHERE name = 'Battle Tower Boss'), NOW()),
    ((SELECT id FROM users WHERE username = 'demo_raihan'),
     (SELECT id FROM teams WHERE name = 'Sinnoh Championship Squad'), NOW()),
    ((SELECT id FROM users WHERE username = 'demo_raihan'),
     (SELECT id FROM teams WHERE name = 'Dynamax Dreams'), NOW()),
    ((SELECT id FROM users WHERE username = 'demo_marnie'),
     (SELECT id FROM teams WHERE name = 'Liberation Team'), NOW()),
    ((SELECT id FROM users WHERE username = 'demo_marnie'),
     (SELECT id FROM teams WHERE name = 'Contrary Leaf Storm'), NOW()),
    ((SELECT id FROM users WHERE username = 'demo_marnie'),
     (SELECT id FROM teams WHERE name = 'Charizard and Friends'), NOW()),
    ((SELECT id FROM users WHERE username = 'demo_marnie'),
     (SELECT id FROM teams WHERE name = 'Fairy Tale'), NOW()),
    ((SELECT id FROM users WHERE username = 'demo_hilda'),
     (SELECT id FROM teams WHERE name = 'Liberation Team'), NOW()),
    ((SELECT id FROM users WHERE username = 'demo_hilda'),
     (SELECT id FROM teams WHERE name = 'Sinnoh Championship Squad'), NOW()),
    ((SELECT id FROM users WHERE username = 'demo_hilda'),
     (SELECT id FROM teams WHERE name = 'Kalos Couture'), NOW()),
    ((SELECT id FROM users WHERE username = 'demo_hilda'),
     (SELECT id FROM teams WHERE name = 'Distortion World Detour'), NOW()),
    ((SELECT id FROM users WHERE username = 'demo_hilda'),
     (SELECT id FROM teams WHERE name = 'Friends Not Tools'), NOW()),
    ((SELECT id FROM users WHERE username = 'demo_gloria'),
     (SELECT id FROM teams WHERE name = 'Charizard and Friends'), NOW()),
    ((SELECT id FROM users WHERE username = 'demo_gloria'),
     (SELECT id FROM teams WHERE name = 'Galar Gauntlet'), NOW()),
    ((SELECT id FROM users WHERE username = 'demo_gloria'),
     (SELECT id FROM teams WHERE name = 'Spikemuth Punk'), NOW()),
    ((SELECT id FROM users WHERE username = 'demo_gloria'),
     (SELECT id FROM teams WHERE name = 'Sandstorm Selfie Squad'), NOW()),
    ((SELECT id FROM users WHERE username = 'demo_gloria'),
     (SELECT id FROM teams WHERE name = 'Battle Tower Boss'), NOW()),
    ((SELECT id FROM users WHERE username = 'demo_serena'),
     (SELECT id FROM teams WHERE name = 'Sinnoh Championship Squad'), NOW()),
    ((SELECT id FROM users WHERE username = 'demo_serena'),
     (SELECT id FROM teams WHERE name = 'Water Ballet'), NOW()),
    ((SELECT id FROM users WHERE username = 'demo_serena'),
     (SELECT id FROM teams WHERE name = 'Contrary Leaf Storm'), NOW()),
    ((SELECT id FROM users WHERE username = 'demo_serena'),
     (SELECT id FROM teams WHERE name = 'Dynamax Dreams'), NOW()),
    ((SELECT id FROM users WHERE username = 'demo_serena'),
     (SELECT id FROM teams WHERE name = 'Charizard and Friends'), NOW()),
    ((SELECT id FROM users WHERE username = 'demo_brendan'),
     (SELECT id FROM teams WHERE name = 'Dragon Den'), NOW()),
    ((SELECT id FROM users WHERE username = 'demo_brendan'),
     (SELECT id FROM teams WHERE name = 'Sootopolis Elegance'), NOW()),
    ((SELECT id FROM users WHERE username = 'demo_brendan'),
     (SELECT id FROM teams WHERE name = 'Charizard and Friends'), NOW()),
    ((SELECT id FROM users WHERE username = 'demo_brendan'),
     (SELECT id FROM teams WHERE name = 'Hulbury Tides'), NOW()),
    ((SELECT id FROM users WHERE username = 'demo_brendan'),
     (SELECT id FROM teams WHERE name = 'Battle Tower Boss'), NOW()),
    ((SELECT id FROM users WHERE username = 'demo_wallace'),
     (SELECT id FROM teams WHERE name = 'Sinnoh Championship Squad'), NOW()),
    ((SELECT id FROM users WHERE username = 'demo_wallace'),
     (SELECT id FROM teams WHERE name = 'Hulbury Tides'), NOW()),
    ((SELECT id FROM users WHERE username = 'demo_wallace'),
     (SELECT id FROM teams WHERE name = 'Kalos Couture'), NOW()),
    ((SELECT id FROM users WHERE username = 'demo_wallace'),
     (SELECT id FROM teams WHERE name = 'Rain Dance Party'), NOW()),
    ((SELECT id FROM users WHERE username = 'demo_n'),
     (SELECT id FROM teams WHERE name = 'Unova Originals'), NOW()),
    ((SELECT id FROM users WHERE username = 'demo_n'),
     (SELECT id FROM teams WHERE name = 'Spikemuth Punk'), NOW()),
    ((SELECT id FROM users WHERE username = 'demo_n'),
     (SELECT id FROM teams WHERE name = 'Sinnoh Championship Squad'), NOW()),
    ((SELECT id FROM users WHERE username = 'demo_n'),
     (SELECT id FROM teams WHERE name = 'Charizard and Friends'), NOW());

COMMIT;

-- Quick sanity check.
SELECT
    (SELECT count(*) FROM users
     WHERE email LIKE '%@demo.brymon.local') AS demo_trainers,
    (SELECT count(*) FROM teams t JOIN users u ON u.id = t.user_id
     WHERE u.email LIKE '%@demo.brymon.local') AS demo_teams,
    (SELECT count(*) FROM teams t JOIN users u ON u.id = t.user_id
     WHERE u.email LIKE '%@demo.brymon.local' AND t.is_public) AS demo_public_teams,
    (SELECT count(*) FROM follows f JOIN users u ON u.id = f.follower_id
     WHERE u.email LIKE '%@demo.brymon.local') AS demo_follows,
    (SELECT count(*) FROM team_likes l JOIN users u ON u.id = l.user_id
     WHERE u.email LIKE '%@demo.brymon.local') AS demo_likes;
